### ISSUE TITLE
Use liberal license on examples

### ISSUE THREAD

**Issue by tfmorris** [nextflow-io/hello#3]
GPL v3 is a super aggressively viral license to use on examples that you want people to be able to freely copy and reuse.

Hello World is, of course, a trivial app to recreate, but it's just unnecessary extra friction in the system.

**Comment by pditommaso** [comment]
Sure thing, that was a legacy of early days https://github.com/nextflow-io/hello/commit/ec11eb0ec77b9f95425695824ca01ffb150699ae

**Comment by tfmorris** [comment]
Thanks!
